[package]
name = "atsc"
version = "0.8.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "An Advanced Time-Series Compressor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
env_logger.workspace = true
log.workspace = true
clap.workspace = true
bincode.workspace = true
rustfft.workspace = true
tempfile.workspace = true
average.workspace = true
regex.workspace = true
hound.workspace = true
median.workspace = true
wavbrro.workspace = true
splines.workspace = true
inverse_distance_weight.workspace = true
num-traits.workspace = true
csv.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true

[lints]
workspace = true

[[bench]]
name = "fft_bench"
harness= false

[[bench]]
name = "polynomial_bench"
harness= false

[[bench]]
name = "decompression_bench"
harness = false
