[package]
name = "tools"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Tools for testing/supporting the development/validation of the compressor"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
wavbrro.workspace = true
hound.workspace = true
chrono.workspace = true
claxon.workspace = true
symphonia.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
regex.workspace = true
median.workspace = true
dtw_rs.workspace = true

[lints]
workspace = true
