name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: build_and_test_${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build_and_test:
    name: Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
      - name: Check `cargo fmt` was run
        run: cargo fmt --all -- --check
      - name: Ensure that all targets compile without warnings
        run: cargo clippy --workspace --all-targets --locked -- -D warnings
      - name: Ensure that all tests pass
        run: cargo test --workspace --all-targets --locked
      - name: Ensure that the decompression benchmark compiles
        run: cargo bench -p atsc --bench decompression_bench --no-run
      - name: Ensure that tests did not create or modify any files that arent .gitignore'd
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status
            exit 1
          fi
