---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  prepublish-check:
    name: "Check that the project is releaseable"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Run checks
        run: atsc/release/is_releasable.sh

  publish-binary:
    name: "Publish Binary to GitHub"
    needs: prepublish-check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Build & test
        run: atsc/release/build_release.sh
      - name: Publish
        uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            *.tar.gz